config/routes.rb
Rails.application.routes.draw do

  get 'items_imports/new'
  get 'items_imports/create'
  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  # devise_scope :user do
  #   post 'users/sign_up', to: 'devise/registrations#create'
  #  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # resources :posts do
  #   resources :likes
  # end

  get '/admin/users', to: 'users/users#index'



  get '/admin/sign_in', to: 'super_user/sign_in#new'
  post '/admin/sign_in', to: 'super_user/sign_in#create'


  get '/admin' , to: 'admin/posts#index'


  get '/admin/create_super_user', to: 'super_user/super_user#new'
  post '/admin/create_super_user', to: 'super_user/super_user#create'
  delete '/admin/super_user', to: 'super_user/super_user#destroy'






  get '/admin/super_users' , to: 'admin/super_users#index'
  get '/admin/super_users/edit' , to: 'admin/super_users#edit'
  put '/admin/super_users/update' , to: 'admin/super_users#update'


  get '/admin/new_role' , to: 'roles/roles#new'
  post '/admin/create_role' , to: 'roles/roles#create'
  get '/admin/create_role/set_cities' , to: 'roles/roles#set_cities'
  get '/admin/create_role/set_offices' , to: 'roles/roles#set_offices'
  get '/admin/roles/edit' , to: 'roles/roles#edit'
  get '/admin/roles' , to: 'roles/roles#index'
  put '/admin/roles' , to: 'roles/roles#update'


  get '/admin/users_report' , to: 'users_report#index'
  get '/admin/user_report' , to: 'users_report#show'
  get '/admin/monthly_report' , to: 'users_report#monthly_report'
  get '/admin/monthly_report/print' , to: 'users_report#print'


  # scope '/admin' do
  #   resources :attendance do
  #     collection do
  #       post :import
  #     end
  #   end
  # end
  get '/admin/attendance' , to: 'attendance#index'
  post '/admin/attendance/load_data' , to: 'attendance#create'

  get '/admin/attendance/export' , to: 'attendance#export'
  get '/admin/attendance/import' , to: 'attendance#import'

  get '/admin/attendance/export_csv' , to: 'attendance#export_csv'

  resources :items_imports ,only: [:index, :new, :create] , path: '/admin/items'

  # resources :user_profile ,only: [:show,:create,:new] , path: '/user_profile'

  get '/user_profile/new' , to: 'user_profile#new'
  get '/user_profile/show' , to: 'user_profile#show'
  post '/user_profile/create' , to: 'user_profile#create'

  get '/user_profile_admin/cites' , to: 'user_profile#cites'

  get '/user_attendance/attendances' , to: 'user_attendance#show'




  get 'user/leaves' , to: 'leave#index'
  get 'user/leave_application' , to: 'leave_requests#new'
  post 'user/leave_application' , to: 'leave_requests#create'
  # put 'user/leave_application'   , to:"line_manager_approval#approve"
  get 'user/recevied_leave_application'   , to:"line_manager_approval#index"
  put 'user/recevied_leave_application'   , to:"line_manager_approval#approve"
  put 'user/reject_recevied_leave_application'   , to:"line_manager_approval#reject"




  get 'admin/leave_applications' , to:"approve#index"
  patch 'admin/leave_applications/approve' , to:"approve#approve"
  patch 'admin/leave_applications/reject' , to:"approve#reject"



  get 'admin/user_workflow' , to:"user_workflows#new"
  post 'admin/user_workflow' , to:"user_workflows#create"
  get 'admin/edit_user_workflow' , to:"user_workflows#edit"
  put 'admin/edit_user_workflow' , to:"user_workflows#update"



  get "admin/country", to:"countries#new"
  post "admin/country", to:"countries#create"



  get 'admin/cities', to:"cities#new"
  post "admin/cities", to:"cities#create"



  get 'admin/office', to:"offices#new"
  post 'admin/office', to:"offices#create"

  get 'admin/category/new', to:"categories#new"
  post 'admin/category/create', to:"categories#create"
  delete 'admin/category/destroy', to:"categories#destroy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/_home.html.erb
<div class="flex   ">


  <div class="md:flex  md:flex-row md:min-h-screen flex-initial ">
    <div class="flex flex-col w-full md:w-64 text-gray-200 bg-gray-900 flex-shrink-0">
      <div class="flex-shrink-0 px-8 py-4 flex flex-row items-center justify-between">
        <a href="#" class="text-xl font-semibold tracking-widest text-gray-200 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">Admin Dashboard</a>
      </div>
      <nav class="flex-grow   px-4 pb-4  bg-gray-800 ">
        <%= link_to "Create Super User" ,  admin_create_super_user_path , class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Users" ,  admin_users_path , class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Super Users" , admin_super_users_path , class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Create New Role" , admin_new_role_path , class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Attendance" , admin_attendance_path , class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Create User Profile" , user_profile_new_path , class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Leave Applications" , admin_leave_applications_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Creating Area" , admin_country_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Crate Category" , admin_category_new_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "Roles" ,admin_roles_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        <%= link_to "User Report" ,admin_users_report_path, class: "block px-4 py-2 mt-2 text-sm font-semibold text-gray-200 bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>

      </nav>
    </div>
  </div>

  <div class="flex flex-col  w-full">

   <div class="flex  p-1 pt-2 justify-between bg-gray-800 w-full h-14  text-gray-200">
    <input class="border-2 w-96 border-gray-100 bg-gray-800 h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none"
           type="search" name="search" placeholder="Search">

     <%= link_to "sign out" , admin_super_user_path,data: {turbo_method: :delete}, class:'text-gray-100  p-4 pt-2 w-max' %>
  </div>

    <div class="  m-3 text-black  ">

      <%= yield :name %>

      <div class="flex justify-center pt-2 w-auto">
        <% flash.each do |type, msg| %>

          <%if type == 'error'%>
            <div data-controller="alert2" class=" fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
              <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded px-4 py-3 rounded relative bg-red-400 border-l-4 border-red-700 text-white pointer-events-auto">
                <div class="p-2">
                  <div class="flex items-start">
                    <div class="ml-3 w-0 flex-1 pt-0.5">
                      <p class="text-sm leading-5 font-medium">
                        <strong class="font-bold"><%=type %>!</strong>
                        <span class="block sm:inline"><%=msg %></span>
                      </p>
                    </div>
                    <div class="ml-4 flex-shrink-0 flex">
                      <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                        </svg>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <%else%>

            <div data-controller="alert2" class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
              <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded px-4 py-3 rounded relative bg-green-400 border-l-4 border-green-700 text-white pointer-events-auto">
                <div class="p-2">
                  <div class="flex items-start">
                    <div class="ml-3 w-0 flex-1 pt-0.5">
                      <p class="text-sm leading-5 font-medium">
                        <strong class="font-bold"><%=type %>!</strong>
                        <span class="block sm:inline"><%=msg %></span>
                      </p>
                    </div>
                    <div class="ml-4 flex-shrink-0 flex">
                      <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                        </svg>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          <%end%>
        <% end %>
      </div>

    </div>
    <div class="">
      <%= yield :admin_content %>
    </div>
  </div>



</div>