config/routes.rb
Rails.application.routes.draw do

  get 'items_imports/new'
  get 'items_imports/create'
  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  # devise_scope :user do
  #   post 'users/sign_up', to: 'devise/registrations#create'
  #  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # resources :posts do
  #   resources :likes
  # end

  get '/admin/users', to: 'users/users#index'



  get '/admin/sign_in', to: 'super_user/sign_in#new'
  post '/admin/sign_in', to: 'super_user/sign_in#create'


  get '/admin' , to: 'admin/posts#index'


  get '/admin/create_super_user', to: 'super_user/super_user#new'
  post '/admin/create_super_user', to: 'super_user/super_user#create'
  delete '/admin/super_user', to: 'super_user/super_user#destroy'






  get '/admin/super_users' , to: 'admin/super_users#index'
  get '/admin/super_users/edit' , to: 'admin/super_users#edit'
  put '/admin/super_users/update' , to: 'admin/super_users#update'


  get '/admin/new_role' , to: 'roles/roles#new'
  post '/admin/create_role' , to: 'roles/roles#create'
  get '/admin/create_role/set_cities' , to: 'roles/roles#set_cities'
  get '/admin/create_role/set_offices' , to: 'roles/roles#set_offices'
  get '/admin/roles/edit' , to: 'roles/roles#edit'
  get '/admin/roles' , to: 'roles/roles#index'
  put '/admin/roles' , to: 'roles/roles#update'


  get '/admin/users_report' , to: 'users_report#index'
  get '/admin/user_report' , to: 'users_report#show'
  get '/admin/monthly_report' , to: 'users_report#monthly_report'
  get '/admin/monthly_report/print' , to: 'users_report#print'


  # scope '/admin' do
  #   resources :attendance do
  #     collection do
  #       post :import
  #     end
  #   end
  # end
  get '/admin/attendance' , to: 'attendance#index'
  post '/admin/attendance/load_data' , to: 'attendance#create'

  get '/admin/attendance/export' , to: 'attendance#export'
  get '/admin/attendance/import' , to: 'attendance#import'

  get '/admin/attendance/export_csv' , to: 'attendance#export_csv'

  resources :items_imports ,only: [:index, :new, :create] , path: '/admin/items'

  # resources :user_profile ,only: [:show,:create,:new] , path: '/user_profile'

  get '/user_profile/new' , to: 'user_profile#new'
  get '/user_profile/show' , to: 'user_profile#show'
  post '/user_profile/create' , to: 'user_profile#create'

  get '/user_profile_admin/cites' , to: 'user_profile#cites'

  get '/user_attendance/attendances' , to: 'user_attendance#show'




  get 'user/leaves' , to: 'leave#index'
  get 'user/leave_application' , to: 'leave_requests#new'
  post 'user/leave_application' , to: 'leave_requests#create'
  # put 'user/leave_application'   , to:"line_manager_approval#approve"
  get 'user/recevied_leave_application'   , to:"line_manager_approval#index"
  put 'user/recevied_leave_application'   , to:"line_manager_approval#approve"
  put 'user/reject_recevied_leave_application'   , to:"line_manager_approval#reject"




  get 'admin/leave_applications' , to:"approve#index"
  patch 'admin/leave_applications/approve' , to:"approve#approve"
  patch 'admin/leave_applications/reject' , to:"approve#reject"



  get 'admin/user_workflow' , to:"user_workflows#new"
  post 'admin/user_workflow' , to:"user_workflows#create"
  get 'admin/edit_user_workflow' , to:"user_workflows#edit"
  put 'admin/edit_user_workflow' , to:"user_workflows#update"



  get "admin/country", to:"countries#new"
  post "admin/country", to:"countries#create"



  get 'admin/cities', to:"cities#new"
  post "admin/cities", to:"cities#create"



  get 'admin/office', to:"offices#new"
  post 'admin/office', to:"offices#create"

  get 'admin/category/new', to:"categories#new"
  post 'admin/category/create', to:"categories#create"
  delete 'admin/category/destroy', to:"categories#destroy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/line_manager_approval_controller.rb
class LineManagerApprovalController < ApplicationController
  before_action :get_leave_request , only: [:approve ,:reject]
  before_action :get_reject_reason, only: [:reject]
  layout('user' )

  def index
    @requests=LeaveRequest.all
    @leave = LeaveRequest.first
    if @leave == nil
      redirect_back fallback_location: user_profile_show_path
    else
      authorize @leave
    end

  end
  def approve
    authorize @request

    puts(@request.aasm(:move).current_state)
    puts(@request.may_final_approve?)
    if @request.may_pre_approve?
      @state = @request.pre_approve!
      redirect_back fallback_location: user_leave_application_path
    elsif @request.may_final_approve?
      @state = @request.final_approve!
      @leave = @request
      @application_type = @leave.leave_type
      @date1 = @leave.leave_start_date.to_date
      @date2 = @leave.leave_end_date.to_date
      @time1 = @leave.leave_start_date.to_time
      @time2 = @leave.leave_end_date.to_time
      @num_of_days=(@date2-@date1).to_i + 1
      @num_of_hours=((@time2 - @time1) / 1.hours).to_i

      if @application_type  == "annual_leave"

        @new_balance = @leave.user.leave.annual_leave.to_i - @num_of_days
        if @leave.user.leave.update_attribute(:annual_leave,@new_balance)
          check_date
          flash[:alert] = "Leave application approved"
          redirect_back fallback_location:user_leave_application_path
        else
          flash[:alert] = "Something went Wrong"
          redirect_back fallback_location:user_leave_application_path
        end
      elsif @application_type  =="sick_leave"
        @new_balance = @leave.user.leave.sick_leave.to_i - @num_of_days
        if @leave.user.leave.update_attribute(:sick_leave,@new_balance)
          check_date
          flash[:alert] = "Leave application approved"
          redirect_back fallback_location:user_leave_application_path
        else
          flash[:alert] = "Something went Wrong"
          redirect_back fallback_location:user_leave_application_path
        end
      elsif @application_type  =="maternity_leave"
        @new_balance = @leave.user.leave.maternity_leave - @num_of_days
        if @leave.user.leave.update_attribute(:maternity_leave,@new_balance)
          check_date
          flash[:alert] = "Leave application approved"
          redirect_back fallback_location:user_leave_application_path
        else
          flash[:alert] = "Something went Wrong"
          redirect_back fallback_location:user_leave_application_path
        end
      elsif @application_type  =="marriage_leave"
        @new_balance = @leave.user.leave.marriage_leave - @num_of_days
        if @leave.user.leave.update_attribute(:marriage_leave,@new_balance)
          check_date
          flash[:alert] = "Leave application approved"
          redirect_back fallback_location:user_leave_application_path
        else
          flash[:alert] = "Something went Wrong"
          redirect_back fallback_location:user_leave_application_path
        end
      elsif @application_type  =="paternity_leave"
        @new_balance = @leave.user.leave.paternity_leave - @num_of_days
        if @leave.user.leave.update_attribute(:paternity_leave,@new_balance)
          check_date
          flash[:alert] = "Leave application approved"
          redirect_back fallback_location:user_leave_application_path
        else
          flash[:alert] = "Something went Wrong"
          redirect_back fallback_location:user_leave_application_path
        end
      elsif @application_type  =="bereavement_leave"
        @new_balance = @leave.user.leave.bereavement_leave - @num_of_days
        if @leave.user.leave.update_attribute(:bereavement_leave,@new_balance)
          check_date
          flash[:alert] = "Leave application approved"
          redirect_back fallback_location:user_leave_application_path
        else
          flash[:alert] = "Something went Wrong"
          redirect_back fallback_location:user_leave_application_path
        end


      elsif @application_type  =="compensatory_off_leave"
      elsif @application_type  =="loss_of_pay_leave"



      elsif @application_type  =="hourly_leave"
        if @leave.user.leave.hourly_leave < @num_of_hours
          @hours= 8
          @leave.user.leave.update_attribute(:hourly_leave,@hours)
          @new_balance = @leave.user.leave.hourly_leave - @num_of_hours
          if @leave.user.leave.update_attribute(:hourly_leave,@new_balance)
            @new_annual_balance = @leave.user.leave.annual_leave.to_i - 1
            @leave.user.leave.update_attribute(:annual_leave,@new_annual_balance)
            check_date
            flash[:alert] = "Leave application approved"
            redirect_back fallback_location:user_leave_application_path
          else
            flash[:alert] = "Something went Wrong"
            redirect_back fallback_location:user_leave_application_path
          end
        else
          @new_balance = @leave.user.leave.hourly_leave - @num_of_hours
          if @leave.user.leave.update_attribute(:hourly_leave,@new_balance)
            check_date
            flash[:alert] = "Leave application approved"
            redirect_back fallback_location:user_leave_application_path
          else
            flash[:alert] = "Something went Wrong"
            redirect_back fallback_location:user_leave_application_path
          end
        end
      else

      end
    end


  end

  def reject
    authorize @request
    if @request.may_reject?
      @state = @request.reject!
      @request.update_attribute(:reject_reason , @reason)
      redirect_back fallback_location:user_leave_application_path
    end
  end


  private

  def check_date

    @start_date = @request.leave_start_date.to_date
    @end_date = @request.leave_end_date.to_date
    @user_id = @request.user_id
    @type = @request.leave_type
    @attendance_last_date = Attendance.last.date

    (@start_date..@end_date).each do |day|
      if day <= @attendance_last_date
        # update attendance expetions
        @attendance = Attendance.find_by(user_id: @user_id ,date: day)
        @attendance.update_attribute(:exception, @type)
      else
        Attendance.new(:user_id=>@user_id,:date=>day,:exception=>@type)
      end
    end


  end

  def get_leave_request
    @request =LeaveRequest.find(params[:id])
  end

  def get_reject_reason
    @reason = params[:leave_request][:reject_reason]
  end

end

app/helpers/line_manager_approval_helper.rb
module LineManagerApprovalHelper
end

app/views/line_manager_approval/_requests.html.erb
<tbody class="bg-white divide-y divide-gray-300">
<tr class="whitespace-nowrap">
  <td class="px-6 py-4">
    <div class="text-sm text-gray-900">
      <%=request.user_id %>
    </div>
  </td>
  <td class="px-6 py-4">
    <div class="text-sm text-gray-500"> <%=request.user.user_profile.nmae%></div>
  </td>
  <td class="px-6 py-4 text-sm text-gray-500">
    <%=request.application_date %>
  </td>

  <td class="px-6 py-4 text-sm text-gray-500">
    <%=request.leave_start_date %>
  </td>

  <td class="px-6 py-4 text-sm text-gray-500">
    <%=request.leave_end_date %>
  </td>


  <td class="px-6 py-4 text-sm text-gray-500">
    <%=request.leave_type %>
  </td>


  <td class="px-6 py-4 text-sm text-gray-500">
    <div> nill </div>
  </td>


  <td class="px-6 py-4 text-sm text-gray-500">
    <%if request.approve.nil? %>
      <%= "" %>
    <%else %>
      <%=request.approve %>
    <%end %>
  </td>


  <td class="px-6 py-4 text-sm text-gray-500">
    <%if request.reason.nil? %>
      <%= "" %>
    <%else %>
      <%=request.reason %>
    <%end %>
  </td>



  <td class="px-6 py-4 text-sm text-gray-500">
    <%if request.certificate.nil? %>
      <%= "" %>
    <%else %>
      <%=request.certificate%>
    <%end %>
  </td>

  <td class="flex px-6 py-4">

    <% if policy(request).approve? %>
      <%= button_to "Approve" , user_recevied_leave_application_path(id:request.id),  method: :put, data: { turbolinks: false }, class:'px-4 py-1 text-sm text-green-400 bg-green-200 rounded-full' %>
  <% end %>

    <%#= form_with  model: request,  url: user_recevied_leave_application_path(id:request.id), method: :put, data: { turbolinks: false }, html: { class: "mx-2" } do |f| %>
      <%#= f.submit "Approve" , class:"px-4 py-1 text-sm text-green-400 bg-green-200 rounded-full" %>
    <%# end %>


    <% if policy(request).reject? %>
      <div data-controller="modal2" data-modal2-allow-background-close="false">
        <a href="#" data-action="click->modal2#open" class="px-4 py-1 text-sm text-red-400 bg-red-200 rounded-full">
          <span>Reject</span>
        </a>

        <!-- Modal Container -->
        <div data-modal2-target="container" data-action="click->modal2#closeBackground keyup@window->modal2#closeWithKeyboard" class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center  justify-center" style="z-index: 9999;">
          <!-- Modal Inner Container -->
          <div class="max-h-screen w-5/12 relative">
            <!-- Modal Card -->
            <div class="m-1 bg-white   rounded shadow ">
              <div class="p-8">
                <h2 class="text-xl mb-4">Reject reason</h2>
                <%= form_with model: request ,url:user_reject_recevied_leave_application_path(id:request.id), method: :put, data: { turbolinks: false },html: {class:"mt-2"} do |f| %>
                  <div class="</div">
                    <%= f.label :"Reject Reason" %><br />
                    <%= f.text_area :reject_reason,  class:"appearance-none mt-1 rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"%>
                  </div>
                  <div class="flex justify-end items-center flex-wrap mt-6">
                    <div class="ml-2 px-4 py-1 text-sm text-indigo-500 hover:bg-indigo-300 bg-indigo-200 rounded-full" data-action="click->modal2#close">Close</div>
                    <%= f.submit "Send reject" ,class:"ml-2 px-4 py-1 text-sm text-red-500 hover:bg-red-300 bg-red-200 rounded-full"%>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
   <% end %>
    <%#= form_for request,  url: admin_leave_applications_reject_path(request), method: :patch, html: { class: "mx-2" } do |f| %>
      <%#= f.submit "Reject" , class:"px-4 py-1 text-sm text-red-400 bg-red-200 rounded-full" %>
    <%# end %>
    <%#= button_to "Reject" , user_reject_recevied_leave_application_path(id:request.id),  method: :put, data: { turbolinks: false }, class:'px-4 py-1 text-sm text-red-400 bg-red-200 rounded-full' %>

    <!--    <button data-controller="modal2" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button" data-modal-toggle="defaultModal">-->
<!--      Toggle modal-->
<!--    </button>-->



  </td>
</tr>

</tbody>

app/views/line_manager_approval/index.html.erb
<% content_for :name do %>

  <p class="flex justify-center text-xl font-bold text-gray-700"> Leave Applications</p>

<% end %>


<% content_for :admin_content do %>
  <div class="overflow-auto">

    <div class="mt-10 mx-3 justify-center ">



      <div class=" border-b border-gray-200 shadow ">
        <table class="divide-y  divide-gray-300 ">
          <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-2  text-gray-700">
              ID
            </th>
            <th class="px-6 py-2 text-gray-700">
              Name
            </th>
            <th class="px-6 py-2 text-gray-700">
              Application Date
            </th>
            <th class="px-6 py-2 text-gray-700">
              Leave Start Date
            </th>
            <th class="px-6 py-2 text-gray-700">
              Leave End Date
            </th>

            <th class="px-6 py-2 text-gray-700">
              Leave Type
            </th>

            <th class="px-6 py-2 text-gray-700">
              Pre Approve
            </th>

            <th class="px-6 py-2 text-gray-700">
              Approve
            </th>

            <th class="px-6 py-2 text-gray-700">
              Reason
            </th>
            <th class="px-6 py-2 text-gray-700">
              Certificate
            </th>
            <th class="px-6 py-2 text-gray-700">
              Action
            </th>


          </tr>
          </thead>

          <%= render partial: "line_manager_approval/requests", collection: @requests , as: :request%>

        </table>
      </div>


    </div>

  </div>
<% end %>