config/routes.rb
Rails.application.routes.draw do

  get 'items_imports/new'
  get 'items_imports/create'
  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  # devise_scope :user do
  #   post 'users/sign_up', to: 'devise/registrations#create'
  #  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # resources :posts do
  #   resources :likes
  # end

  get '/admin/users', to: 'users/users#index'



  get '/admin/sign_in', to: 'super_user/sign_in#new'
  post '/admin/sign_in', to: 'super_user/sign_in#create'


  get '/admin' , to: 'admin/posts#index'


  get '/admin/create_super_user', to: 'super_user/super_user#new'
  post '/admin/create_super_user', to: 'super_user/super_user#create'
  delete '/admin/super_user', to: 'super_user/super_user#destroy'






  get '/admin/super_users' , to: 'admin/super_users#index'
  get '/admin/super_users/edit' , to: 'admin/super_users#edit'
  put '/admin/super_users/update' , to: 'admin/super_users#update'


  get '/admin/new_role' , to: 'roles/roles#new'
  post '/admin/create_role' , to: 'roles/roles#create'
  get '/admin/create_role/set_cities' , to: 'roles/roles#set_cities'
  get '/admin/create_role/set_offices' , to: 'roles/roles#set_offices'
  get '/admin/roles/edit' , to: 'roles/roles#edit'
  get '/admin/roles' , to: 'roles/roles#index'
  put '/admin/roles' , to: 'roles/roles#update'


  get '/admin/users_report' , to: 'users_report#index'
  get '/admin/user_report' , to: 'users_report#show'
  get '/admin/monthly_report' , to: 'users_report#monthly_report'
  get '/admin/monthly_report/print' , to: 'users_report#print'


  # scope '/admin' do
  #   resources :attendance do
  #     collection do
  #       post :import
  #     end
  #   end
  # end
  get '/admin/attendance' , to: 'attendance#index'
  post '/admin/attendance/load_data' , to: 'attendance#create'

  get '/admin/attendance/export' , to: 'attendance#export'
  get '/admin/attendance/import' , to: 'attendance#import'

  get '/admin/attendance/export_csv' , to: 'attendance#export_csv'

  resources :items_imports ,only: [:index, :new, :create] , path: '/admin/items'

  # resources :user_profile ,only: [:show,:create,:new] , path: '/user_profile'

  get '/user_profile/new' , to: 'user_profile#new'
  get '/user_profile/show' , to: 'user_profile#show'
  post '/user_profile/create' , to: 'user_profile#create'

  get '/user_profile_admin/cites' , to: 'user_profile#cites'

  get '/user_attendance/attendances' , to: 'user_attendance#show'




  get 'user/leaves' , to: 'leave#index'
  get 'user/leave_application' , to: 'leave_requests#new'
  post 'user/leave_application' , to: 'leave_requests#create'
  # put 'user/leave_application'   , to:"line_manager_approval#approve"
  get 'user/recevied_leave_application'   , to:"line_manager_approval#index"
  put 'user/recevied_leave_application'   , to:"line_manager_approval#approve"
  put 'user/reject_recevied_leave_application'   , to:"line_manager_approval#reject"




  get 'admin/leave_applications' , to:"approve#index"
  patch 'admin/leave_applications/approve' , to:"approve#approve"
  patch 'admin/leave_applications/reject' , to:"approve#reject"



  get 'admin/user_workflow' , to:"user_workflows#new"
  post 'admin/user_workflow' , to:"user_workflows#create"
  get 'admin/edit_user_workflow' , to:"user_workflows#edit"
  put 'admin/edit_user_workflow' , to:"user_workflows#update"



  get "admin/country", to:"countries#new"
  post "admin/country", to:"countries#create"



  get 'admin/cities', to:"cities#new"
  post "admin/cities", to:"cities#create"



  get 'admin/office', to:"offices#new"
  post 'admin/office', to:"offices#create"

  get 'admin/category/new', to:"categories#new"
  post 'admin/category/create', to:"categories#create"
  delete 'admin/category/destroy', to:"categories#destroy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_workflow.rb
class UserWorkflow < ApplicationRecord
    belongs_to :office
    has_many :users
    has_one :line_manager, foreign_key: 'line_manager_id', class_name: 'User'
    # around_create :update_user_workflow


    scope :hr_officers, ->{where('SELECT * FROM user_profiles WHERE position = %hr% ')}

    before_update do
        self.users.ids.each do |id|
            @user = User.find_by(id: id)
            @user.update!(user_workflow_id:0)
            end
    end

    # private
    #
    # def update_user_workflow
    #     puts('callback')
    #     puts(self.workflow_name)
    # end
end

app/controllers/user_workflows_controller.rb
class UserWorkflowsController < ApplicationController
    before_action :authorized_admin
    before_action :set_workflow_prams, only: [:edit,:update]
    layout('admin' )

    def new
        @users = User.all
        @office = get_office
        @user_workflows = UserWorkflow.all
    end
     
    def create
        puts(params)
        @office = Office.find(params[:office_id])
        @hr_officer = @office.hr_officer
        puts(@hr_officer.email)
        puts(params)
        @new_workflow= get_office.user_workflows.create!(get_params)
        if @new_workflow.save
            ActiveRecord::Base.transaction do
                params[:user][:employees].each do |id|
                    if id != ''
                    @user = User.find_by(id:id)
                    @user.update!(user_workflow_id:@new_workflow.id, line_manager_id: params[:user][:workflow_manager] )
                    @user_profile = UserProfile.find_by(user_id:id)
                    @user_profile.update!(working_office:params[:office_id] , line_manager: params[:user][:workflow_manager] )
                    end
                end

            rescue ActiveRecord::RecordInvalid
                puts "Oops. We tried to do an invalid operation!"
            end
            redirect_to admin_office_path(:city_id => get_office.city.id)

        else
            flash[:alert] = "tried to do an invalid operation"
            redirect_to admin_office_path(:city_id => get_office.city.id)
        end
    end

    def edit
        @users = User.all
        @current_users = @workflow.users.ids.to_a
        @line_manager=User.find_by(id:@workflow.workflow_manager).id
        @office = Office.first
    end

    def update
        @office = Office.find_by(id:@workflow.office_id)
        puts(@office)
        if @workflow.update(get_params)

            ActiveRecord::Base.transaction do
                params[:user][:employees].each do |id|
                    if id != ''
                        @user = User.find_by(id:id)
                        @user.update!(user_workflow_id:@workflow.id )
                        @user_profile = UserProfile.find_by(user_id:id)
                        @user_profile.update!(line_manager: params[:user][:workflow_manager] )
                    end
                end

            rescue ActiveRecord::RecordInvalid
                puts "Oops. We tried to do an invalid operation!"
            end
            redirect_to admin_user_workflow_path(:office_id => @office.city.id)

        else
            render :edit
        end
    end


    private

    def get_office
        Office.find(params[:office_id])
    end

    def get_params
        params.require(:user).permit(:workflow_name , :workflow_manager)
    end

    def set_workflow_prams
        @workflow = UserWorkflow.find_by(id: params[:workflow_id])
    end



end

app/helpers/user_workflows_helper.rb
module UserWorkflowsHelper
end

app/views/user_workflows/_user_workflows.html.erb
<div>
  <div class="m-3 text-xl font-bold text-gray-900 ">
    <ul  style="list-style-type:disc;" >
      <li >
        <div class="flex flex-col justify-center">
          <%=link_to "#{workflow.workflow_name}", admin_edit_user_workflow_path(workflow_id: workflow.id)%>
          <span class="w-1/3 mt-3  mr-6 p-0.5 bg-gray-800 "></span>
          <div class="flex mt-3 text-lg font-medium text-gray-700">

            <%if workflow.users.length > 0 %>
            <% workflow.users.each do |user| %>
                            <p class=""><%=user.user_profile.nmae%>,</p>
            <%end%>
            <%else%>
                          <p>Edit</p>
            <%end %>

          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/user_workflows/edit.html.erb
<div class="flex justify-center w-auto">

  <% flash.each do |type, msg| %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"><%=type %>!</strong>
      <span class="block sm:inline"><%=msg %></span>

    </div>
  <% end %>
</div>
<% content_for :name do %>
  Edit Workflow : <%=@workflow.workflow_name %>
<% end %>


<% content_for :admin_content do %>
  <div class="m-3">


    <%= form_with model: @users ,url:admin_edit_user_workflow_path(:workflow_id => @workflow.id) , remote: true ,method: :PUT , html: {class:"mt-8  flex "} do |f| %>
      <div class="flex flex-col  w-full justify-center items-center">

        <div class="w-1/2">
          <%= f.label :"Workflow Name:"%><br />
          <%= f.text_field :workflow_name,
            class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm",
           value:@workflow.workflow_name
          %>
        </div>

        <div class="w-1/2">
          <%= f.label :"Workflow Manager Email:" %><br />
          <% options = options_from_collection_for_select(@users, 'id' , 'email' ,@line_manager) %>
          <%= f.select :workflow_manager,  options,{ include_blank: true } , class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"%>
        </div>

        <div class="container">
          <%= f.label :"Employees:"%><br />
          <%= f.select :employees, options_from_collection_for_select(@users, 'id' , 'email',@current_users),{ include_blank: true } ,
                       data:{controller:"select2" , select2_options_value:{hideSelectedOption: true, showSearch: true , class: 'dropdown-container', placeholder: t('actions.click_to_add_lists')}.to_json},
                       multiple:'multiple'
          %>

        </div>

        <div class="m-3">
          <%= f.submit "Update Workflow" ,class:"group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>

        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/user_workflows/new.html.erb
<div class="flex justify-center w-auto">

  <% flash.each do |type, msg| %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"><%=type %>!</strong>
      <span class="block sm:inline"><%=msg %></span>

    </div>
  <% end %>
</div>
<% content_for :name do %>
  <p>Office : <%=@office.name %></p>
<% end %>


<% content_for :admin_content do %>
  <div class="m-3" >
        <div class="m-3">

        
            <%= form_with model: @users ,url:admin_user_workflow_path(:office_id => @office.id) , remote: true , html: {class:"mt-8  flex "} do |f| %>
              <div class="flex flex-col  w-full justify-center items-center">

                <div class="w-1/2">
                  <%= f.label :"Workflow Name:"%><br />
                  <%= f.text_field :workflow_name, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"%>
                </div>

                <div class="w-1/2">
                  <%= f.label :"Workflow Manager Email:" %><br />
                  <% options = options_from_collection_for_select(@users, 'id' , 'email' ) %>
                  <%= f.select :workflow_manager,  options,{ include_blank: true } , class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"%>
                </div>

                <div class="container">
                  <%= f.label :"Employees:"%><br />
                  <%= f.select :employees, options_from_collection_for_select(@users, 'id' , 'email'),{ include_blank: true } ,
                               data:{controller:"select2" , select2_options_value:{hideSelectedOption: true, showSearch: true , class: 'dropdown-container', placeholder: t('actions.click_to_add_lists')}.to_json},
                                 multiple:'multiple'
                  %>

                </div>

                   <div class="m-3">
                     <%= f.submit "Create Profile" ,class:"group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>

                   </div>
              </div>
            <% end %>
        </div>

    <%= render partial: "user_workflows/user_workflows" , collection:  @user_workflows,  as: :workflow%>
    
    </div>




<% end %>